version: '3.7'

services:
  elasticsearch:
    environment:
      - ELASTIC_DEFAULT_USER=elastic
      - ELASTIC_PASSWORD=elastic
      - network.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic

  grafana:
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - GF_INSTALL_PLUGINS=agenty-flowcharting-panel
      - ELASTICSEARCH_INDEX=logstash*
    ports:
      - "3000:3000"

  python:
    env_file:
      - ./envs/elasticsearch.env
