name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:

    deploy:
      name: Deploy
      runs-on: [self-hosted]

      steps:

        - name: Checkout
          uses: actions/checkout@v3

        - name: Reload containers
          shell: bash
          run: |
            sudo docker compose stop
            sudo docker compose up -d

        - name: Installing the service
          shell: bash
          run: |
            bash ./install.sh

